USE BookMS;

CREATE TABLE USERLEVEL
(
  LEVELNAME VARCHAR(100) NOT NULL, #等级
/*
    professor: 教师
    undergraduate: 本科生
    graduate: 研究生
    doctor: 博士
 */
  BORROWNUM INT NOT NULL,  #可借本数
  PERIOD INT NOT NULL,		#借阅期限
  PRIMARY KEY(LEVELNAME)
);

CREATE TABLE READER
(
  RID VARCHAR(11) NOT NULL,  #ID
  PASSWORD VARCHAR(20) NOT NULL, #密码
  RNAME VARCHAR(50), #姓名
  REMAIL VARCHAR(50), #邮箱
  LEVELNAME VARCHAR(100) NOT NULL, #等级
  PRIMARY KEY(RID),
  FOREIGN KEY(LEVELNAME) REFERENCES USERLEVEL(LEVELNAME)
);

CREATE TABLE OFFICER
(
  OID VARCHAR(11) NOT NULL, #ID
  PASSWORD VARCHAR(20) NOT NULL, #密码
  ONAME VARCHAR(50), #姓名
  OEMAIL VARCHAR(50), #邮箱
  PRIMARY KEY(OID)
);

CREATE TABLE ADMIN
(
  AID VARCHAR(11) NOT NULL, #ID
  PASSWORD VARCHAR(20) NOT NULL, #密码
  ANAME VARCHAR(50), #姓名
  AEMAIL VARCHAR(50), #邮箱
  PRIMARY KEY(AID)
);

CREATE TABLE BOOKINFO
(
  ISBN VARCHAR(100) NOT NULL,
  BINDEX VARCHAR(100) NOT NULL, #索引号
  BNAME VARCHAR(100),
  BAUTHOR VARCHAR(100), #作者
  BPRESS VARCHAR(100), #出版社
  BYEAR INT, #年份
  PRIMARY KEY(ISBN)
);

CREATE TABLE SINGLEBOOK
(
  BOOKID VARCHAR(100) NOT NULL, #条码
  ISBN VARCHAR(100) NOT NULL, #ISBN
  BPLACE VARCHAR(100), #馆藏
  BSTATE INT, #状态
  /*
    -1:  购买中
    0:   在架上
    1:   被借阅
    2:   被预约
   */
  BCANBORROW BOOLEAN, #是否可借阅
  /*
    0: 保留图书/不可借阅
    1: 出借图书
   */
  PRIMARY KEY(BOOKID),
  FOREIGN KEY(ISBN) REFERENCES BOOKINFO(ISBN)
);

CREATE TABLE BORROWINFO
(
  BORROWID VARCHAR(100), #处理编号
  RID VARCHAR(11) NOT NULL, #读者ID
  BOOKID VARCHAR(100) NOT NULL, #条码
  BORROWTIME DATE, #借阅时间
  RETURNTIME DATE, #归还/应还时间
  ISRETURN BOOLEAN, #是否已归还
  PRIMARY KEY(BORROWID),
  FOREIGN KEY(RID) REFERENCES READER(RID),
  FOREIGN KEY(BOOKID) REFERENCES SINGLEBOOK(BOOKID)
);
