USE BookMS;

CREATE TABLE READER
(
  RID VARCHAR(11) NOT NULL, #ID
  PASSWORD VARCHAR(20) NOT NULL, #密码
  RNAME VARCHAR(50), #姓名
  REMAIL VARCHAR(50), #邮箱
  PRIMARY KEY(RID)
);

CREATE TABLE OFFICER
(
  OID VARCHAR(11) NOT NULL, #ID
  PASSWORD VARCHAR(20) NOT NULL, #密码
  ONAME VARCHAR(50), #姓名
  OEMAIL VARCHAR(50), #邮箱
  PRIMARY KEY(OID)
);

CREATE TABLE ADMIN
(
  AID VARCHAR(11) NOT NULL, #ID
  PASSWORD VARCHAR(20) NOT NULL, #密码
  ANAME VARCHAR(50), #姓名
  AEMAIL VARCHAR(50), #邮箱
  PRIMARY KEY(AID)
);

CREATE TABLE USERLEVEL 
(
  LEVELNAME VARCHAR(100) NOT NULL, #读者等级
  BORROWNUM INT NOT NULL,  #可借本数
  PRIMARY KEY(LEVELNAME)
);

CREATE TABLE SINGLEBOOK
(
  BOOKID VARCHAR(100) NOT NULL, #条码
  ISBN VARCHAR(100) NOT NULL, #ISBN 
  BPLACE VARCHAR(100), #馆藏
  BSTATE VARCHAR(100), #状态
  BCANBORROW BOOLEAN, #是否可借阅
  PRIMARY KEY(BOOKID)
);

CREATE TABLE BOOKINFO
(
  ISBN VARCHAR(100) NOT NULL,
  BINDEX VARCHAR(100) NOT NULL, #索引号
  BNAME VARCHAR(100), 
  BAUTHOR VARCHAR(100), #作者
  BPRESS VARCHAR(100), #出版社
  BYEAR VARCHAR(100), #年份
  PRIMARY KEY(ISBN)
);

CREATE TABLE BORROWINFO
(
  BORROWID VARCHAR(100), #处理编号
  RID VARCHAR(11) NOT NULL, #读者ID
  BOOKID VARCHAR(100) NOT NULL, #条码
  BORROWTIME DATE, #借阅时间
  RETURNTIME DATE, #归还/应还时间
  ISRETURN BOOLEAN, #是否已归还
  PRIMARY KEY(BORROWID)
);

